package com.pruebas_concepto.demo_hipotecaria;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class request implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Fecha de radicacion")
	private java.util.Date fechaSolicitud;
	@org.kie.api.definition.type.Label(value = "Nombre")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label(value = "Apellido")
	private java.lang.String apellido;
	@org.kie.api.definition.type.Label(value = "Tipo de identificacion")
	private java.lang.String tipoIdentificacion;
	@org.kie.api.definition.type.Label(value = "Identificacion")
	private java.lang.Integer identificacion;
	@org.kie.api.definition.type.Label(value = "Telefono")
	private java.lang.String telefono;
	@org.kie.api.definition.type.Label(value = "Correo Electronico")
	private java.lang.String email;

	public request() {
	}

	public java.util.Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(java.util.Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getApellido() {
		return this.apellido;
	}

	public void setApellido(java.lang.String apellido) {
		this.apellido = apellido;
	}

	public java.lang.String getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(java.lang.String tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	public java.lang.Integer getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(java.lang.Integer identificacion) {
		this.identificacion = identificacion;
	}

	public java.lang.String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(java.lang.String telefono) {
		this.telefono = telefono;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public request(java.util.Date fechaSolicitud, java.lang.String nombre,
			java.lang.String apellido, java.lang.String tipoIdentificacion,
			java.lang.Integer identificacion, java.lang.String telefono,
			java.lang.String email) {
		this.fechaSolicitud = fechaSolicitud;
		this.nombre = nombre;
		this.apellido = apellido;
		this.tipoIdentificacion = tipoIdentificacion;
		this.identificacion = identificacion;
		this.telefono = telefono;
		this.email = email;
	}

}